apiVersion: v1
kind: Service
metadata:
  name: moviedetailsservice
  namespace: dev
spec:
  selector:
    app: moviedetails
    # give this when there is pods and service for selector and labels --
    #release: 0
    environment: dev

  ports:
  - name: http
    port: 8087
# if you are running on any cloud provider remove the nodePort and change type as LoadBalancer
  type: LoadBalancer
